apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: web-route
  namespace: default
spec:
  http:
    - name: web
      match:
        paths:
          - "/web"
      backends:
        - serviceName: web1-svc
          servicePort: 80
          weight: 70
        - serviceName: web2-svc
          servicePort: 80
          weight: 30
      plugins:
        - name: prometheus
          enable: true
      websocket: true
      timeout:
        connect: 10s
        send: 10s
        read: 10s
