apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
  namespace: apisix
  labels:
    app.kubernetes.io/name: apisix
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 9443
      protocol: TCP
    - name: admin
      port: 9180
      targetPort: 9180
      protocol: TCP
    - name: control
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app.kubernetes.io/name: apisix
